### ISSUE TITLE
在boot.json中"name"應該是"Terraria Expand Mod"

### ISSUE THREAD

**Issue by Paul-16098** [Nephthelana/DOL-Terra-Expanding-Modd#1]
![image](https://github.com/user-attachments/assets/c67e7300-99e3-4185-b16d-03e48659c379)
![image](https://github.com/user-attachments/assets/fc7abd03-2539-4e0f-adc8-5099e416272b)

**Comment by Nephthelana** [comment]
嗷，我这样标记名称的话，是不是会影响到以我的模组作为前置模组的情况？我之前是希望在模组管理器界面加载后，能直接看到模组的版本号。那我之后会在名称里把版本号删去的。谢谢！
