### ISSUE TITLE
建議: 快捷键设置添加開關以禁用快捷鍵

### ISSUE THREAD

**Issue by Paul-16098** [Nephthelana/DOL-Terra-Expanding-Modd#2]
![image](https://github.com/user-attachments/assets/4b036fcd-ede5-4a38-8d95-b1d14e90ea61)

**Comment by Nephthelana** [comment]
谢谢你的建议！我已经添加了禁用快捷键的功能，将在下个版本可用！
<img alt="禁用状态" src="https://github.com/user-attachments/assets/fd86f7fb-7331-482e-96f5-91ee03cf18f0">
<img alt="启用状态" src="https://github.com/user-attachments/assets/e6cd494b-12b4-4403-b594-a3d5cbdde6ae">
